GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "John",
    "age": "16"
}

###
PATCH http://localhost:5000/users/66f26c3a2b8fe4c6a4d5eb5c
Content-Type: application/json 

{
    "name": "John Update"
}

###
DELETE http://localhost:5000/users/66f68bc04585964be34cd77c

